### ISSUE TITLE
Code related problems

### ISSUE THREAD

**Issue by Zeyu1226-mt** [renjie-liang/HUAL#1]
Hello, after reading your paper, I feel that your work is very good and meaningful. When will your code be open source?

**Comment by renjie-liang** [comment]
Hi, thanks for your attention, I will release a draft version within a week.

**Comment by renjie-liang** [comment]
Hi, I push my code into GitHub, but there are still some bugs when inferring. You can read the part about generating pseudo labels first.

**Comment by renjie-liang** [comment]
Hi, I push my code into GitHub, but there are still some bugs when inferring. You can read the part about generating pseudo labels first.
